format = """
$username$hostname$directory$git_branch$git_status$nodejs$bun$character
"""

[directory]
style = "bold cyan"
truncation_length = 3

[git_branch]
style = "bold purple"

[git_status]
style = "red"

[nodejs]
format = "via [$symbol($version )]($style)"
style = "bold green"

[bun]
format = "via [$symbol($version )]($style)"
style = "bold red"
symbol = "ğŸ¥Ÿ "

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"
